//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DBContext
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class Discount
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Discount()
        {
            this.Discount_detail = new HashSet<Discount_detail>();
        }
    
        public short discount_id { get; set; }
        public string discount_content { get; set; }
        public Nullable<decimal> discount_value { get; set; }
        public string discount_code { get; set; }
        public Nullable<decimal> discount_minimum_order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Discount_detail> Discount_detail { get; set; }
    }
}
