//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.DBContext
{
	using Newtonsoft.Json;
	using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.Discount_detail = new HashSet<Discount_detail>();
            this.Restaurants = new HashSet<Restaurant>();
            this.User_order = new HashSet<User_order>();
        }
    
        public short user_id { get; set; }
        public string user_name { get; set; }
        public string user_email { get; set; }
        public string user_sex { get; set; }
        public string user_password { get; set; }
        public string user_image { get; set; }
        public string user_phone { get; set; }
        public string user_address { get; set; }
        public Nullable<short> user_role_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Discount_detail> Discount_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<Restaurant> Restaurants { get; set; }
        [JsonIgnore]
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        [JsonIgnore]
        public virtual ICollection<User_order> User_order { get; set; }
    }
}
